import { beforeEach, describe, expect, it } from "vitest";
import { BaseLLMProvider } from "../../providers/base.js";
import {
  LLMEvent,
  LLMProviderError,
  LLMRequest,
  LLMResponse,
  ModelDescriptor,
  ProviderHealth,
} from "../../providers/types.js";
import { ModelRegistry } from "../../registry/modelRegistry.js";
import { LLMRouter } from "../router.js";

class MockProvider extends BaseLLMProvider {
  constructor(
    readonly id: string,
    readonly name: string,
    private readonly models: ModelDescriptor[],
    private readonly onGenerate?: (req: LLMRequest) => Promise<LLMResponse>
  ) {
    super();
  }

  async listModels(): Promise<ModelDescriptor[]> {
    return this.models;
  }

  async healthCheck(): Promise<ProviderHealth> {
    return { healthy: true, latencyMs: 20, checkedAt: Date.now() };
  }

  async generate(request: LLMRequest): Promise<LLMResponse> {
    if (this.onGenerate) {
      return this.onGenerate(request);
    }
    return {
      providerId: this.id,
      modelId: request.modelId,
      text: `Generated by ${request.modelId}`,
      finishReason: "stop",
      usage: { promptTokens: 10, completionTokens: 10, totalTokens: 20 },
      latencyMs: 25,
    };
  }

  async *stream(_request: LLMRequest): AsyncIterable<LLMEvent> {
    yield { type: "text_delta", text: "chunk" };
    yield { type: "done", finishReason: "stop" };
  }
}

describe("LLMRouter", () => {
  let registry: ModelRegistry;
  let router: LLMRouter;

  const lightModel: ModelDescriptor = {
    providerId: "mock-fast",
    modelId: "model-light",
    displayName: "Mock Fast Light",
    availability: "available",
    pricing: { inputCostPer1k: 0, outputCostPer1k: 0, isFree: true, currency: "USD" },
    contextWindow: 32768,
    maxOutputTokens: 4096,
    capabilities: {
      coding: true,
      reasoning: false,
      vision: false,
      toolCalling: true,
      structuredOutput: true,
      streaming: true,
    },
    estimatedQuality: {
      coding: 0.72,
      reasoning: 0.6,
      debugging: 0.65,
      planning: 0.6,
      summarization: 0.75,
      classification: 0.8,
    },
    runtime: {
      latency: 20,
      tokensPerSecond: 200,
      successRate: 1.0,
      recentFailures: 0,
      rateLimitedUntil: null,
      remainingQuota: null,
    },
  };

  const proModel: ModelDescriptor = {
    providerId: "mock-smart",
    modelId: "model-pro",
    displayName: "Mock Smart Pro",
    availability: "available",
    pricing: { inputCostPer1k: 0.005, outputCostPer1k: 0.015, isFree: false, currency: "USD" },
    contextWindow: 128000,
    maxOutputTokens: 8192,
    capabilities: {
      coding: true,
      reasoning: true,
      vision: true,
      toolCalling: true,
      structuredOutput: true,
      streaming: true,
    },
    estimatedQuality: {
      coding: 0.95,
      reasoning: 0.96,
      debugging: 0.94,
      planning: 0.95,
      summarization: 0.95,
      classification: 0.95,
    },
    runtime: {
      latency: 100,
      tokensPerSecond: 60,
      successRate: 1.0,
      recentFailures: 0,
      rateLimitedUntil: null,
      remainingQuota: null,
    },
  };

  const freeReasoningModel: ModelDescriptor = {
    providerId: "mock-free-smart",
    modelId: "model-free-70b",
    displayName: "Mock Free 70B",
    availability: "available",
    pricing: { inputCostPer1k: 0, outputCostPer1k: 0, isFree: true, currency: "USD" },
    contextWindow: 65536,
    maxOutputTokens: 8192,
    capabilities: {
      coding: true,
      reasoning: true,
      vision: false,
      toolCalling: true,
      structuredOutput: true,
      streaming: true,
    },
    estimatedQuality: {
      coding: 0.88,
      reasoning: 0.89,
      debugging: 0.85,
      planning: 0.86,
      summarization: 0.88,
      classification: 0.9,
    },
    runtime: {
      latency: 50,
      tokensPerSecond: 120,
      successRate: 0.99,
      recentFailures: 0,
      rateLimitedUntil: null,
      remainingQuota: null,
    },
  };

  beforeEach(async () => {
    registry = new ModelRegistry();
    const p1 = new MockProvider("mock-fast", "Fast", [lightModel]);
    const p2 = new MockProvider("mock-smart", "Smart", [proModel]);
    const p3 = new MockProvider("mock-free-smart", "FreeSmart", [freeReasoningModel]);

    registry.registerProvider(p1);
    registry.registerProvider(p2);
    registry.registerProvider(p3);
    await registry.refreshModels();

    router = new LLMRouter(registry);
  });

  it("routes trivial tasks to economical free model", () => {
    const decision = router.route("rename variable x to count");
    expect(decision.classification.complexityClass).toBe("TRIVIAL");
    expect(decision.selectedModel.modelId).toBe("model-light");
  });

  it("routes complex tasks to capable model while prioritizing free options", () => {
    const decision = router.route(
      "refactor multi-file architectural race conditions between daemon and websocket"
    );
    expect(decision.classification.complexityClass).toBe("COMPLEX");
    // Free high-capability model should beat paid model under free-first policy
    expect(decision.selectedModel.modelId).toBe("model-free-70b");
  });

  it("strictly filters paid models when allowPaidFallback is false", () => {
    const decision = router.route(
      "refactor multi-file architectural race conditions between daemon and websocket",
      { allowPaidFallback: false }
    );
    expect(decision.selectedModel.pricing.isFree).toBe(true);

    // If no free model meets the critical 0.9 floor, it throws QUOTA_EXHAUSTED
    expect(() => {
      router.route("mission critical security audit of cryptographic token generation", {
        allowPaidFallback: false,
      });
    }).toThrowError(LLMProviderError);
  });

  it("automatically fails over upon HTTP 429 rate limit without task failure", async () => {
    const failingProvider = new MockProvider("mock-fast", "Fast", [lightModel], async (req) => {
      if (req.modelId === "model-light") {
        throw new LLMProviderError("RATE_LIMIT", "429 Resource Exhausted", true, 30000);
      }
      return {
        providerId: "mock-fast",
        modelId: req.modelId,
        text: "Success from fallback",
        finishReason: "stop",
        usage: { promptTokens: 5, completionTokens: 5, totalTokens: 10 },
        latencyMs: 15,
      };
    });

    registry.registerProvider(failingProvider);

    const response = await router.execute({
      modelId: "auto",
      messages: [{ role: "user", content: "rename variable foo to bar" }],
    });

    expect(response.text).toBeDefined();
    expect(response.failovers).toBeDefined();
    expect(response.failovers?.[0]).toContain("Rate limit (429)");

    // Verify model-light is now actively rate-limited in the registry
    const light = registry.getModel("mock-fast", "model-light");
    expect(light?.runtime.rateLimitedUntil).toBeGreaterThan(Date.now());
  });
});
